import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/homepage/Navbar";
import Footer from "@/components/homepage/Footer";
import { Suspense } from "react";
import Marquee from "@/components/homepage/Marque";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-right" />
        <Suspense
          fallback={
            <h1 className="text-xl font-bold text-[#000000]">
              Loading navigation...
            </h1>
          }
        >
          <Navbar />
        </Suspense>

        <Suspense
          fallback={
            <h2 className="text-xl font-bold text-[#000000]">
              Loading Marque...
            </h2>
          }
        >
          <Marquee />
        </Suspense>

        {children}

        <Footer />
      </body>
    </html>
  );
}
